"""init power components, users, likes

Revision ID: 9af21a825ea3
Revises: 
Create Date: 2026-09-16 02:39:21.539928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af21a825ea3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('power_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('power_watt', sa.Integer(), nullable=True),
    sa.Column('weight_gram', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('formed_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'deleted')", name='ck_power_components_status'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_power_components_id'), 'power_components', ['id'], unique=False)
    op.create_index('uq_one_draft_per_creator', 'power_components', ['creator_id'], unique=True, postgresql_where=sa.text("status = 'draft'"))
    op.create_table('power_component_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('power_component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['power_component_id'], ['power_components.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'power_component_id', name='uq_user_component_like')
    )
    op.create_index(op.f('ix_power_component_likes_id'), 'power_component_likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_power_component_likes_id'), table_name='power_component_likes')
    op.drop_table('power_component_likes')
    op.drop_index('uq_one_draft_per_creator', table_name='power_components', postgresql_where=sa.text("status = 'draft'"))
    op.drop_index(op.f('ix_power_components_id'), table_name='power_components')
    op.drop_table('power_components')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
